//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practic3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Equipment = new HashSet<Equipment>();
            this.Furniture = new HashSet<Furniture>();
            this.User = new HashSet<User>();
            this.Workers_on_order = new HashSet<Workers_on_order>();
        }
    
        public long ID { get; set; }
        public string First_name { get; set; }
        public string Last_name { get; set; }
        public string Midle_name { get; set; }
        public System.DateTime Born_date { get; set; }
        public long Position_at_work { get; set; }
        public decimal Wages { get; set; }
        public decimal Passport_serial { get; set; }
        public decimal Passport_number { get; set; }
        public string Registration { get; set; }
        public string E_mail { get; set; }
        public string Phone_number { get; set; }
    
        public virtual Job_title Job_title { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equipment> Equipment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Furniture> Furniture { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Workers_on_order> Workers_on_order { get; set; }
    }
}
