//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practic3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Furniture_materials
    {
        public long ID { get; set; }
        public long Furniture { get; set; }
        public long Material { get; set; }
    
        public virtual Furniture Furniture1 { get; set; }
        public virtual Material Material1 { get; set; }
    }
}
