//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practic3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class furniture_centreEntities : DbContext
    {
        public furniture_centreEntities()
            : base("name=furniture_centreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Equipment> Equipment { get; set; }
        public virtual DbSet<Furniture> Furniture { get; set; }
        public virtual DbSet<Furniture_materials> Furniture_materials { get; set; }
        public virtual DbSet<Job_title> Job_title { get; set; }
        public virtual DbSet<Material> Material { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<Repair_request> Repair_request { get; set; }
        public virtual DbSet<Service> Service { get; set; }
        public virtual DbSet<Services_in_order> Services_in_order { get; set; }
        public virtual DbSet<Status_of_order> Status_of_order { get; set; }
        public virtual DbSet<Status_of_request> Status_of_request { get; set; }
        public virtual DbSet<Supplier> Supplier { get; set; }
        public virtual DbSet<Supply> Supply { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Type_of_furniture> Type_of_furniture { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Workers_on_order> Workers_on_order { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
    }
}
